# Generated by Django 4.2.6 on 2023-10-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='image.jpg', upload_to='image/%Y-%m/', verbose_name='Изображение публикации'),
            preserve_default=False,
        ),
    ]
