# Generated by Django 4.2.6 on 2023-10-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y-%m/', verbose_name='Изображение публикации'),
        ),
    ]
