# Generated by Django 4.2.6 on 2023-10-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_likes_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IP-адрес'),
        ),
    ]
